// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-west-2",
  "aws_cognito_identity_pool_id": "us-west-2:34979291-3516-45f2-bdec-6e3087a7ba78",
  "aws_cognito_region": "us-west-2",
  "aws_user_pools_id": "us-west-2_wf2PodP2N",
  "aws_user_pools_web_client_id": "4gngb6omip5bt6ca73uoof006l",
  "oauth": {
    "domain": "newphotoshare-local.auth.us-west-2.amazoncognito.com",
    "scope": [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "http://localhost:3000/",
    "redirectSignOut": "http://localhost:3000/",
    "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
